### ISSUE TITLE
Problem with running the examples in Linux

### ISSUE THREAD

**Issue by serpheroth** [RippeR37/GLUL#30]
I was able to get the library compiled, but when I tried to run the examples, the program just gets stuck there after it is executed, no window is popped up.
What I did was to compile the binary under the src folder of the example, then move the exe file to the bin directory

**Comment by RippeR37** [comment]
Please provide more information on how did you build examples, which example (is it one or each), maybe post zip file with your project settings, files, compiled files etc. which i could check myself?

I don't have too much time right now to build whole lib and examples and test it, but if you could upload your whole project directory i might find a little time to check it out and see if i can help you with it. Also check for .log files where you have executable file (logLibrary.log and/or logOpenGL.log files) and see if there are no informations that could help.

Also confirm that you use fixed library code from `develop` branch, not fixed-by-yourslef.

**Comment by serpheroth** [comment]
You can download entire project from
`https://www.dropbox.com/s/ogruy6ya1isltz9/Utility-Library-develop.zip?dl=0`
I used qmake to build the library, so if want to recompile the library, you may install the qmake.
run `qmake && make` to compile the library.
Then go to `examples/basic`, and run `make`, the binary is compiled into `basic/bin/`
I also tested the models example, it has the same problem.
After I run the exe, no log file is generated.

To get the code compiled, I commented out the `std::put_time` line and
`Context.cpp, line 42, glDebugMessageCallbackARB(&Context::logError, nullptr);`

**Comment by serpheroth** [comment]
I tried to look into the issue. The program gets stuck when it calls glfwInit() function

**Comment by RippeR37** [comment]
@serpheroth: I have to ask, does any simple GLEW/GLFW program (like example from their sites) work for you? It could be somehow problem with your computer (graphic drivers or something like that) or some bug in _GLEW_ library?

I didn't have time to test it out yet, but i'll try tommorow to check it on my platform.

**Comment by serpheroth** [comment]
I tried to run the examples that come with the GLFW library, they run without any problem.

**Comment by RippeR37** [comment]
I did compile library and example with GCC 4.9 and CodeBlocks as IDE, but i ran into same problem as you had.

Replacing window creation with some simple GLFW/GLEW initialization without any of my code seems to do the trick on creating window, i have yet to find real problem behind it. Also there is similar problem with Logger class - it freezes on attempt to create stream or write to it. So it may in fact be the reason why your code got stuck (since Window class uses Logger) and probably it is the reason.

I'll check more for this on Windows and GCC. I dont have time now to fully fix it and push new version, but i'll try later or tommorow to do that.

**Comment by RippeR37** [comment]
@serpheroth
I've looked into the problem and it turns out it wasn't on glfwInit() but it was problem with `Logger` class. I've changed some methods and added new one to obtain library's stream and now it works like a charm. Tested both on Windows with VS2013 and on Ubuntu 14.04 with GCC 4.8.2.

This fix will soon be merged into master branch and tagged as version 0.1.1.

**Comment by RippeR37** [comment]
`Master` branch is now merged with this fix and tagged as version `0.1.1`.

**Comment by serpheroth** [comment]
I tested under Mac OS 10.10 and got the error message
"[Error]: [GLFW] Error 65543: NSGL: The targeted version of OS X only supports forward-compatible contexts for OpenGL 3.2 and above"
in logLibrary.log.

**Comment by RippeR37** [comment]
@serpheroth 
According to [this](https://www.opengl.org/wiki/Core_And_Compatibility_in_Contexts) (Forward compatibility chapter) and [this](https://open.gl/context#comment-1097383597), Mac OS have some weird requirement, that if application using _OpenGL_ is requesting context for version >= 3.2, then it HAS TO send _forward compatibility_ bit set. This in fact have no any meaning, since in >= 3.2 compatibility mode it doesn't remove anything and in >= 3.2 core profiles it removes like one feature at all (wide lines). So it's exactly problem with library, rather very specific requirement for given os that can be matched using it.

To deal with it you can:
- Use `Window`'s method to achieve just that: `Window::setHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)`
  - **Remember:** If you use `setHint()` or `setHints()` method before creation of Window, no default hints will be set. So if you still want 3.3 core profile context, you should use method `Window::setDefaultHints()`, or set them by yourself. To see which hints are available look [here](http://www.glfw.org/docs/latest/window.html#window_hints)
- Use GLFW's function before creating window `glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)`

I'm afraid i can't test it myself, as i don't own any Mac hardware, but it should work. I'm not so confident to add this auto-hint to OS-specific problem, becouse it actually could leave you without some functionality and thus break existing code. I'll read more on that later and decide.

If it will work, please give me a note not to worry too much :)

**Comment by serpheroth** [comment]
By calling `Window::setHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE)` and modifying the shader files, I was able to run the `basic` example.

**Comment by serpheroth** [comment]
I further tested it under Linux Mint 17.1. `basic` example works fine, but `framework` and `model` examples raised segmentation fault once they were ran. No output in the logLibrary file. The gdb tells that the fault happens at Util::Interface::State::_onUnload()

**Comment by RippeR37** [comment]
Glad earlier tip helped.

It appears that new error was in `FW::Application` class, it didn't initialize pointer to `nullptr` value at start. It seems that VS compiler does this by itself, but GCC just leaves that chunck of memory like it was before. Added initialization and fixed minor things like supress warnings and/or fixed typos in path address.

Be aware, that library's shaders are in `/bin/` folder and to use some examples (like _models example_) you have to copy these to example folder. Only assets tied with specific example are present in it's folder, general assets are tied to library. Just for the heads-up if you would build this example to.

Also merged changes with master and fixed _release_ to point to new version. I tested myself all examples on Windows and Linux and for now, it should be over. Anyway, thanks for testing it out and i hope you'll like it. :)
